### ISSUE TITLE
2.0.0 Release Readiness

### ISSUE THREAD

**Issue by rrati** [blackducksoftware/opssight-connector#17]
For the 2.0.0 release we need to update a few items once they are ready:

- [ ] Tag source with 2.0.0 label
- [x] Create 2.0 branch
- [x] Update installer to point to 2.0.0 container tags for openshift and kubernetes
- [x] Update components from upstream
- [ ] Complete docs/wiki

**Comment by msenmurugan** [comment]
created 2.0.0 branch

**Comment by msenmurugan** [comment]
The tags are updated to 2.0.0

**Comment by jayunit100** [comment]
- Im about ready to check docs/wiki.  Meanwhile.:
- senthil is updating all the source from upstream, creating the 2.0 branch, 2.0.0 label, and 2.0.0. container tags

**Comment by rrati** [comment]
@msenmurugan How can we have a 2.0.0 tag when we don't have a 2.0.0 release?  We should only tag 2.0.0 when we release 2.0.0
