### ISSUE TITLE
Long image names: unable to update annotations/labels for pod... must be no more than 63 characters

### ISSUE THREAD

**Issue by sheppduck** [blackducksoftware/opssight-connector#23]
The perceiver can come across images with long names and the following error is throw in the log:
time="2018-04-18T17:21:19Z" level=error msg="unable to update annotations/labels for pod openshift-template-service-broker:apiserver-lz5tb: Pod \"apiserver-lz5tb\" is invalid: metadata.labels: Invalid value: \"registry.access.redhat.com.openshift3.ose-template-service-broker\": must be no more than 63 characters"

Looks like we should maybe be ignoring the registry name, if possible?

matching upstream issue: https://github.com/blackducksoftware/perceivers/issues/61

**Comment by rrati** [comment]
Closed via #29
