### ISSUE TITLE
Install error due to latest tags not found in docker

### ISSUE THREAD

**Issue by davemeurer** [blackducksoftware/opssight-connector#7]
the image-registry.json file had the latest tags, and our images aren't up in docker yet, so I had to replace latest with 2.0.0-RC

errors below:
serviceaccount "protoform" created
ddcluster role "cluster-admin" added: "system:serviceaccount:bds-perceptor:protoform"
cluster role "cluster-admin" added: "system:serviceaccount:bds-perceptor:perceiver"
serviceaccount "perceptor-scanner-sa" created
scc "privileged" added to: ["system:serviceaccount:bds-perceptor:perceptor-scanner-sa"]
cluster role "cluster-admin" added: "system:serviceaccount:bds-perceptor:perceptor-scanner-sa"
role "view" added: "system:serviceaccount::perceptor-scanner-sa"
Error from server (NotFound): routes "docker-registry" not found
Error from server (NotFound): services "docker-registry" not found
Error from server (NotFound): services "docker-registry" not found
pod "protoform" created
secret "viper-secret" created

**Comment by jayunit100** [comment]
We should definetly fix the dockerhub builds to have the `latest` images and `master` images for alpha testers per releases ~
