### ISSUE TITLE
SHA string in project and version causing some formatting issues in Hub

### ISSUE THREAD

**Issue by davemeurer** [blackducksoftware/opssight-connector#8]
The SHA string in project and version names are causing some formatting issues in certain pages of the Hub:

The Where Used page
![image](https://user-images.githubusercontent.com/5341483/38442857-ac0e8382-39b7-11e8-9ecf-29c00a8a13f6.png)

Not so much a formatting issue, but boy... so many characters in the header:
![image](https://user-images.githubusercontent.com/5341483/38442978-2456527a-39b8-11e8-8417-8fc6af2ccdbf.png)

This brings up another question, if the image changes, I'm assuming it will get a new SHA.  Will that image go under the same project in Hub, or will a new project be created?

**Comment by msenmurugan** [comment]
@davemeurer It will create a new project and version

Why the OpsSight is creating new project?
All the images will be uniquely identified by SHA. Once the perceptor is started/restarted, it will check whether the image have been already scanner or not in hub using SHA. If yes, it will pull the corresponding image(reference by SHA) vulnerability and policy violations from Hub.

**Comment by mattfenwick** [comment]
Done in https://github.com/blackducksoftware/perceptor/pull/136
